SELECT distinct str (?id ) AS ?ccid ?accNum
FROM <http://glycoinfo.org/database/pdb>
WHERE { 
?resource <http://purl.org/dc/terms/identifier> ?id .
?s <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> glycan:Saccharide .
?s <http://purl.jp/bio/12/glyco/glycan#has_resource_entry> ?resource .
?s <http://purl.org/dc/terms/identifier> ?accNum .
  VALUES ?accNum {"{{accessionNumber}}"}
}
